-- PropertyLedger seed categories — spec §3. Run after schema.sql.
-- System categories (is_system = true, user_id null) are visible to every user and cannot be deleted in-app.
-- Mortgage split into Interest/Principal: interest is tax-deductible, principal is not.
insert into categories (name, kind, is_system) values
  ('Insurance','expense',true),
  ('School Tax','expense',true),
  ('County Tax','expense',true),
  ('City/Township Tax','expense',true),
  ('Water','expense',true),
  ('Sewer','expense',true),
  ('Garbage','expense',true),
  ('Electric','expense',true),
  ('Gas/Heating','expense',true),
  ('Internet/Cable','expense',true),
  ('HOA Fees','expense',true),
  ('Mortgage Interest','expense',true),
  ('Mortgage Principal','expense',true),
  ('Repairs','expense',true),
  ('Maintenance','expense',true),
  ('Landscaping/Snow','expense',true),
  ('Pest Control','expense',true),
  ('Cleaning','expense',true),
  ('Property Management Fee','expense',true),
  ('Legal/Professional Fees','expense',true),
  ('Advertising/Listing','expense',true),
  ('Supplies','expense',true),
  ('Appliances','expense',true),
  ('Capital Improvement','expense',true),
  ('Permits/Licenses','expense',true),
  ('Travel/Mileage','expense',true),
  ('Bank/Loan Fees','expense',true),
  ('Other Expense','expense',true),
  ('Rent','income',true),
  ('Late Fee','income',true),
  ('Pet Fee','income',true),
  ('Security Deposit Retained','income',true),
  ('Laundry/Vending','income',true),
  ('Parking','income',true),
  ('Insurance Payout','income',true),
  ('Other Income','income',true);

-- Personal budget categories
update categories set scope = 'both'
 where is_system = true and name in (
  'Insurance','Water','Sewer','Garbage','Electric','Gas/Heating','Internet/Cable',
  'HOA Fees','Repairs','Maintenance','Cleaning','Supplies','Appliances',
  'Legal/Professional Fees','Bank/Loan Fees','Other Expense','Other Income');

insert into categories (name, kind, is_system, scope) values
  ('Groceries','expense',true,'personal'),
  ('Dining Out','expense',true,'personal'),
  ('Rent/Mortgage','expense',true,'personal'),
  ('Car Payment','expense',true,'personal'),
  ('Car Insurance','expense',true,'personal'),
  ('Fuel','expense',true,'personal'),
  ('Public Transit','expense',true,'personal'),
  ('Phone','expense',true,'personal'),
  ('Health/Medical','expense',true,'personal'),
  ('Childcare','expense',true,'personal'),
  ('Education','expense',true,'personal'),
  ('Subscriptions','expense',true,'personal'),
  ('Clothing','expense',true,'personal'),
  ('Personal Care','expense',true,'personal'),
  ('Entertainment','expense',true,'personal'),
  ('Gifts','expense',true,'personal'),
  ('Travel','expense',true,'personal'),
  ('Charity','expense',true,'personal'),
  ('Debt Payment','expense',true,'personal'),
  ('Savings Transfer','expense',true,'personal'),
  ('Salary','income',true,'personal'),
  ('Bonus','income',true,'personal'),
  ('Freelance','income',true,'personal'),
  ('Interest/Dividends','income',true,'personal'),
  ('Refund','income',true,'personal'),
  ('Gift Received','income',true,'personal');
