-- PropertyLedger seed categories — spec §3. Run after schema.sql.
-- System categories (is_system = true, user_id null) are visible to every user and cannot be deleted in-app.
-- Mortgage split into Interest/Principal: interest is tax-deductible, principal is not.
insert into categories (name, kind, is_system) values
  ('Insurance','expense',true),
  ('School Tax','expense',true),
  ('County Tax','expense',true),
  ('City/Township Tax','expense',true),
  ('Water','expense',true),
  ('Sewer','expense',true),
  ('Garbage','expense',true),
  ('Electric','expense',true),
  ('Gas/Heating','expense',true),
  ('Internet/Cable','expense',true),
  ('HOA Fees','expense',true),
  ('Mortgage Interest','expense',true),
  ('Mortgage Principal','expense',true),
  ('Repairs','expense',true),
  ('Maintenance','expense',true),
  ('Landscaping/Snow','expense',true),
  ('Pest Control','expense',true),
  ('Cleaning','expense',true),
  ('Property Management Fee','expense',true),
  ('Legal/Professional Fees','expense',true),
  ('Advertising/Listing','expense',true),
  ('Supplies','expense',true),
  ('Appliances','expense',true),
  ('Capital Improvement','expense',true),
  ('Permits/Licenses','expense',true),
  ('Travel/Mileage','expense',true),
  ('Bank/Loan Fees','expense',true),
  ('Other Expense','expense',true),
  ('Rent','income',true),
  ('Late Fee','income',true),
  ('Pet Fee','income',true),
  ('Security Deposit Retained','income',true),
  ('Laundry/Vending','income',true),
  ('Parking','income',true),
  ('Insurance Payout','income',true),
  ('Other Income','income',true);
