// Data access for the expenses table.
import { supabase } from './supabase';
import type { Expense, NewExpense } from '@/types';

/** Inserts an expense for the signed-in user (RLS requires the explicit user_id). */
export async function createExpense(input: NewExpense): Promise<Expense> {
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData?.user) throw new Error('Not signed in.');
  const { data, error } = await supabase
    .from('expenses')
    .insert({ ...input, user_id: userData.user.id })
    .select()
    .single();
  if (error) throw error;
  return data as Expense;
}

/** Every expense the user owns (RLS-scoped) — feeds the P&L/report math. */
export async function listAllExpenses(): Promise<Expense[]> {
  const { data, error } = await supabase
    .from('expenses')
    .select('*')
    .order('paid_on', { ascending: false });
  if (error) throw error;
  return (data ?? []) as Expense[];
}

/** All expenses for a property, newest paid_on first (timeline source). */
export async function listPropertyExpenses(propertyId: string): Promise<Expense[]> {
  const { data, error } = await supabase
    .from('expenses')
    .select('*')
    .eq('property_id', propertyId)
    .order('paid_on', { ascending: false });
  if (error) throw error;
  return (data ?? []) as Expense[];
}

/** One expense by id (for the edit screen). */
export async function getExpense(id: string): Promise<Expense> {
  const { data, error } = await supabase.from('expenses').select('*').eq('id', id).single();
  if (error) throw error;
  return data as Expense;
}

/** Updates editable fields on an expense. */
export async function updateExpense(id: string, patch: Partial<NewExpense>): Promise<Expense> {
  const { data, error } = await supabase
    .from('expenses')
    .update(patch)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as Expense;
}

/** Deletes an expense. Callers must confirm first (confirmDelete, spec §5 Phase 7). */
export async function deleteExpense(id: string): Promise<void> {
  const { error } = await supabase.from('expenses').delete().eq('id', id);
  if (error) throw error;
}

/** Rows generated by (still linked to) a recurring rule — the engine's idempotency input. */
export async function listExpensesForRule(recurringId: string): Promise<Expense[]> {
  const { data, error } = await supabase
    .from('expenses')
    .select('*')
    .eq('recurring_id', recurringId)
    .order('paid_on', { ascending: true });
  if (error) throw error;
  return (data ?? []) as Expense[];
}

/** Bulk insert (recurring catch-up). Empty input is a no-op with no network call. */
export async function createExpenses(inputs: NewExpense[]): Promise<Expense[]> {
  if (inputs.length === 0) return [];
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData?.user) throw new Error('Not signed in.');
  const userId = userData.user.id;
  const { data, error } = await supabase
    .from('expenses')
    .insert(inputs.map((input) => ({ ...input, user_id: userId })))
    .select();
  if (error) throw error;
  return (data ?? []) as Expense[];
}
