// Data access for the income table (mirror of expenses — spec §5 Phase 6).
import { supabase } from './supabase';
import type { Income, NewIncome } from '@/types';

/** Inserts an income entry for the signed-in user (RLS requires the explicit user_id). */
export async function createIncome(input: NewIncome): Promise<Income> {
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData?.user) throw new Error('Not signed in.');
  const { data, error } = await supabase
    .from('income')
    .insert({ ...input, user_id: userData.user.id })
    .select()
    .single();
  if (error) throw error;
  return data as Income;
}

/** Every income row the user owns (RLS-scoped) — feeds the P&L/report math. */
export async function listAllIncome(): Promise<Income[]> {
  const { data, error } = await supabase
    .from('income')
    .select('*')
    .order('received_on', { ascending: false });
  if (error) throw error;
  return (data ?? []) as Income[];
}

/** All income for a property, newest received_on first (timeline source). */
export async function listPropertyIncome(propertyId: string): Promise<Income[]> {
  const { data, error } = await supabase
    .from('income')
    .select('*')
    .eq('property_id', propertyId)
    .order('received_on', { ascending: false });
  if (error) throw error;
  return (data ?? []) as Income[];
}

/** One income entry by id (for the edit screen). */
export async function getIncome(id: string): Promise<Income> {
  const { data, error } = await supabase.from('income').select('*').eq('id', id).single();
  if (error) throw error;
  return data as Income;
}

/** Updates editable fields on an income entry. */
export async function updateIncome(id: string, patch: Partial<NewIncome>): Promise<Income> {
  const { data, error } = await supabase
    .from('income')
    .update(patch)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as Income;
}

/** Deletes an income entry. Callers must confirm first (confirmDelete, spec §5 Phase 7). */
export async function deleteIncome(id: string): Promise<void> {
  const { error } = await supabase.from('income').delete().eq('id', id);
  if (error) throw error;
}

/** Rows generated by (still linked to) a recurring rule — the engine's idempotency input. */
export async function listIncomeForRule(recurringId: string): Promise<Income[]> {
  const { data, error } = await supabase
    .from('income')
    .select('*')
    .eq('recurring_id', recurringId)
    .order('received_on', { ascending: true });
  if (error) throw error;
  return (data ?? []) as Income[];
}

/** Bulk insert (recurring catch-up). Empty input is a no-op with no network call. */
export async function createIncomes(inputs: NewIncome[]): Promise<Income[]> {
  if (inputs.length === 0) return [];
  const { data: userData, error: userError } = await supabase.auth.getUser();
  if (userError || !userData?.user) throw new Error('Not signed in.');
  const userId = userData.user.id;
  const { data, error } = await supabase
    .from('income')
    .insert(inputs.map((input) => ({ ...input, user_id: userId })))
    .select();
  if (error) throw error;
  return (data ?? []) as Income[];
}
