// Shared domain types — mirror the Postgres schema in supabase/schema.sql.
// Dates are ISO strings (YYYY-MM-DD); money is a number in dollars backed by numeric(12,2).

export type PropertyType = 'rental' | 'personal';

/** A row in the properties table. */
export interface Property {
  id: string;
  user_id: string;
  name: string;
  address: string | null;
  property_type: PropertyType;
  purchase_date: string | null;
  purchase_price: number | null;
  notes: string | null;
  is_archived: boolean;
  created_at: string;
}

/** Which ledger a category belongs to. */
export type CategoryKind = 'expense' | 'income';

/** A row in the categories table. System rows (user_id null) are seeded and undeletable. */
export interface Category {
  id: string;
  user_id: string | null;
  name: string;
  kind: CategoryKind;
  is_system: boolean;
  created_at: string;
}

/** A row in the expenses table. */
export interface Expense {
  id: string;
  user_id: string;
  property_id: string;
  category_id: string;
  amount: number;
  paid_on: string;
  period_start: string | null;
  period_end: string | null;
  vendor: string | null;
  notes: string | null;
  /** Set when this row was generated by a recurring rule; null for manual entries. */
  recurring_id: string | null;
  /** True once the user edits a generated row — the generator never touches it again. */
  is_edited: boolean;
  created_at: string;
}

/** Client-supplied fields when creating an expense. */
export interface NewExpense {
  property_id: string;
  category_id: string;
  amount: number;
  paid_on: string;
  period_start?: string | null;
  period_end?: string | null;
  vendor?: string | null;
  notes?: string | null;
  recurring_id?: string | null;
  is_edited?: boolean;
}

/** A row in the income table. */
export interface Income {
  id: string;
  user_id: string;
  property_id: string;
  category_id: string;
  amount: number;
  received_on: string;
  source: string | null;
  notes: string | null;
  /** Set when this row was generated by a recurring rule; null for manual entries. */
  recurring_id: string | null;
  /** True once the user edits a generated row — the generator never touches it again. */
  is_edited: boolean;
  created_at: string;
}

/** Client-supplied fields when creating an income entry. */
export interface NewIncome {
  property_id: string;
  category_id: string;
  amount: number;
  received_on: string;
  source?: string | null;
  notes?: string | null;
  recurring_id?: string | null;
  is_edited?: boolean;
}

/** Client-supplied fields when creating a property (id/user_id/created_at are server-side). */
export interface NewProperty {
  name: string;
  property_type: PropertyType;
  address?: string | null;
  purchase_date?: string | null;
  purchase_price?: number | null;
  notes?: string | null;
}

/** How a recurring rule ends (README §4.1). */
export type EndMode = 'count' | 'until_stopped';

/** A row in the recurring_rules table — the template that spawns one entry per month. */
export interface RecurringRule {
  id: string;
  user_id: string;
  property_id: string;
  category_id: string;
  kind: CategoryKind;
  amount: number;
  notes: string | null;
  /** First day of the first month, e.g. '2026-01-01'. */
  start_month: string;
  end_mode: EndMode;
  /** Required when end_mode === 'count'; null otherwise. */
  occurrences: number | null;
  /** Set when an until_stopped rule is stopped (README §4.4). */
  stopped_on: string | null;
  /** First-of-month dates the user deleted; the generator never re-posts them (README §4.3 delete). */
  skipped_months: string[];
  is_active: boolean;
  created_at: string;
}

/** Client-supplied fields when creating a rule (id/user_id/created_at/stopped_on/is_active are server-side). */
export interface NewRecurringRule {
  property_id: string;
  category_id: string;
  kind: CategoryKind;
  amount: number;
  notes?: string | null;
  start_month: string;
  end_mode: EndMode;
  occurrences?: number | null;
}
